const toBool = (x) => x == 'true'
const { Sequelize } = require('sequelize')
const { existsSync } = require('fs')
if (existsSync('config.env')) require('dotenv').config({ path: './config.env' })
module.exports = {
    VERSION: 'V 1.0.0',
    SESSION_ID: process.env.SESSION_ID || 'bixby~6R6DU6APQGIuo2k8SOby+4Oiv1eQhcaW',
    PASSWORD: process.env.PASSWORD || '',
    REACT : process.env.REACT || 'false',
    GROUP_CHAT : process.env.GROUP_CHAT || 'false',
    FREE_TXT : process.env.FREE_TXT || 'bixbymd',
    U_STATUS: process.env.U_STATUS || 'true',
    ALIVETXT: process.env.ALIVETXT || 'WHATSBIXBY MD',
    ALIVE_DATA : process.env.ALIVE_DATA || "https://i.imgur.com/DyLAuEh.jpg;aliveText;alivebButtenText1;aliveTextButten2",
    MENTION: process.env.MENTION || 'on',
    BOT_INFO : process.env.BOT_INFO || "WHATSBIXBY-MD,BOT,https://i.imgur.com/DyLAuEh.jpg",
    BGMBOT : process.env.BGMBOT || 'false',
    WORKTYPE: process.env.WORKTYPE || 'public',
    PM_BLOCK : process.env.PM_BLOCK || "false",
    CALL_BLOCK : process.env.CALL_BLOCK || "false",
    LANG :process.env.LANG || 'EN', //values are ml, en only
    OWNER : process.env.OWNER || "919446072492",
    BRANCH: 'master',
    PROCFILE_DATA : process.env.PROCFILE_DATA || "💗 ᴀᴜᴛᴏ ᴍᴀᴛɪᴄ ʙɪᴏ -ʙᴏᴛ-ᴍᴅ",
    ANTILINK : process.env.ANTILINK || 'youtube',
    ANTIFAKE : process.env.ANTIFAKE || '+2222',
    ALL_LINK_BAN : process.env.ALL_LINK_BAN || 'false',
    SEND_READ: process.env.SEND_READ === undefined ? false : convertToBool(process.env.SEND_READ),
    HEROKU: {
        HEROKU: process.env.HEROKU === undefined ? false : convertToBool(process.env.HEROKU),
        API_KEY: process.env.HEROKU_API_KEY || '',
        APP_NAME: process.env.HEROKU_APP_NAME || ''
    },
    BLOCK_CHAT : process.env.BLOCK_CHAT ||[],
    AUTO_CHAT_PM : process.env.AUTO_CHAT_PM || "false",
    AUTO_CHAT_GRP : process.env.AUTO_CHAT_GRP || "false",
    BOT_PRESENCE : process.env.BOT_PRESENCE || "recording",
    IS_PRESENCE : process.env.IS_PRESENCE || "false",
    CHATBOT : process.env.CHATBOT || 'null',
    FOOTER : process.env.FOOTER || "ɪɴʀʟ-ᴍᴅ",
    ALIVE : process.env.ALIVE || "https://i.imgur.com/DyLAuEh.jpg",
    IMG11 : process.env.IMG11 || "https://i.imgur.com/DyLAuEh.jpg",
    IMG12 : process.env.IMG12 || "https://imgur.com/AelfUJg.jpg",
    ERRIMG : process.env.ERRIMG || "https://imgur.com/ggvhL6C.jpg",
    INSTAGRAM : process.env.INSTAGRAM || "https://instagram.com/_user_not_define",
    PACKNAME : process.env.PACKNAME || "ɪɴʀʟ-ʙᴏᴛ",
    GIT : process.env.GIT || "https://tinyurl.com/3ex3e48e",
    WEB : process.env.WEB || "https://tinyurl.com/ycks3s8p",
    YT : process.env.YT || "https://tinyurl.com/36r3668n",
    CAPTION : process.env.CAPTION || "Created by WhatsBixby-MD",
    SUDO: process.env.SUDO || "919446072492",
    VIDEO : "https://tinyurl.com/3x38ajmn",
    WAGRP : process.env.WAGRP || 'https://tinyurl.com/f5wh55mk',
    };
